kind: PersistentVolume
apiVersion: v1
metadata:
  name: aditya-postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/aditya/sqldata/"
    type: "DirectoryOrCreate"