apiVersion: batch/v1
kind: Job
metadata:
  name: pipedream-train
spec:
  template:
    spec:
      containers:
      - image: nvcr.io/nvidia/pytorch:19.05-py3
        name: train-container
        volumeMounts:
        - mountPath: /home/aditya
          name: main-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: OnFailure
      volumes:
      - name: main-volume
        hostPath:
          path: /home/aditya/
          type: Directory